### ISSUE TITLE
Watch doesn't detect addition / deletion of files

### ISSUE THREAD

**Issue by rbabayoff** [wilr/grunt-shopify#45]
Only file changes are detected.

Platform: ubuntu 12.04.5 guest running on a windows virtualbox host.

Maybe worth to consider moving to https://github.com/paulmillr/chokidar, which is supposedly more robust and is used by karma, among others? Will be happy to work on a pull request for that.

**Comment by jhenriquez** [comment]
This is related to an [issue][1] in the watch project. We only need to prepending './' in the configuration since cwd is always assumed. I didn't go any deeper into the reasons of this :)

But it's working fine now. @rbabayoff, this can be closed.

[1]: https://github.com/gruntjs/grunt-contrib-watch/issues/282
